### ISSUE TITLE
Underlying (and useful) exception details are hidden

### ISSUE THREAD

**Issue by morrissimo** [awslabs/aws-encryption-sdk-python#10] opened 2017-08-29 20:17 UTC
This has bitten me numerous times!

All of the following instances catch `ClientError` from botocore and re-raise a new generic (and remarkably useless by comparison) exception:
* `key_providers.kms._generate_data_key:L213`
* `key_providers.kms._encrypt_data_key:L250`
* `key_providers.kms._decrypt_data_key:L283`

I believe a different approach should be taken here to prevent hiding botocore Client exception details (network connectivity, insufficient permissions, etc).

**Comment by mattsb42-aws** [comment] 2017-08-29 20:34
We intentionally normalize the exceptions raised in order to maintain a consistent API across all master keys.  This is important not only for consistency, but also because not all master key implementations will want to expose to the runtime why they failed, just that they did.

In this case, I think it is reasonable to make the underlying exception details available.  What we can do is log the original exception details.  That maintains the API promise but also gives you the cause of the underlying exception in your debug logs.

**Comment by morrissimo** [comment] 2017-08-29 20:50
Sounds good - thanks for the quick response

**Comment by mattsb42-aws** [comment] 2017-09-12 23:34
This is addressed in #12

**Closed by mattsb42-aws** 2017-09-12 23:34 UTC
Labels: bug
